server:
  port: 8088
  context-path: /sm

## 配置数据源相关信息
spring:
  druid: #druid监控页面用户名和密码
    name: admin
    pass: sailing123
  datasource:
    name: DBconfig
    type: com.alibaba.druid.pool.DruidDataSource
    initialize: true
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  redis:
    host: 127.0.0.1  # redis服务所在的地址
    port: 6379
    password:   # redis的密码默认为空
    pool:
      max-active: 8  #连接池最大连接数（使用负值表示没有限制）
      max-idle: 8  #连接池最大空闲数
      min-idle: 1  #连接池最小空闲数
      max-wait: 60000  #获取连接的超时等待事件
    timeout: 30000  #连接redis服务器的最大等待时间

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapperXML/*.xml  # 注意：一定要对应mapper映射xml文件的所在路径
  config-location: classpath:MybatisConfig.xml # 注意: mybatis的配置文件
  type-aliases-package: com.sailing.springbootmybatis.bean # 注意：对应实体类的路径

## 配置分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=conutSql






